Consider the following nonlinear function: f(x) = ($x_{1}$ + 10*$x_{2}$)**2 + 5*($x_{3}$ - $x_{4}$)**4 + 10*($x_{1}$ - $x_{4}$)**4.
The initial guess x0 = [3;-1;0;1], step length alpha = 0.001, and the convergence threshold is set to 0.01. 

Modify the in-class code to preform the gradient descent method. Also will need to state the iterations and the final x values at convergence.

In [3]:
# import the libraries
import numpy as np
import math

In [4]:
## a function returns the Gradient vector at the input vector x_i
## note: the expression of each element in the Gradient vector is hard-coded based on the formula presented above, which is also given on Slide 40 of Topic 3.1

#this part is modified for our function when using partial derivatives of each x1-4. g[0] corresponds to our partial derivative of x1, and etc
def getGradientVector(x_i):
  g = np.zeros((4,1))   #(amount of x_i, 1)
  g[0] = 2 * (x_i[0] + 10*x_i[1]) + 40*(x_i[0] - x_i[3])**3
  g[1] = 20 * (x_i[0] + 10 * x_i[1])
  g[2] = 20 * (x_i[2] - x_i[3])**3
  g[3] = -20 * (x_i[2] - x_i[3])**3 - 40 * (x_i[0] - x_i[3])**3
  return g

# a simple function returns the norm of an input vector
def getNorm(v):
  return math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2] + v[3]*v[3])   #v[x_i]*v[x_i]

In [5]:
## set an initial guess
x_0 = np.array([[3.0], [-1.0], [0.0], [1.0]]) #we got this initial guess given in the problem
print(f"--The initial guess x0: ")
print(x_0)

## set a threshold value for getting a good solution (given in problem)
thresh = 0.01

## set step length (given in problem)
alpha = 0.001


#this whole part and onward is not edited 
x_i = x_0
count = 0
while True:
  print('****************************************************')
  print(f'--At iteration: {count}')
  
  ## compute the gradient vector at x_i
  g = getGradientVector(x_i)
  print(f"--The gradient vector g(x_{count}): ")
  print(g)

  ## compute the norm of the gradient vector at x_i
  normOfGradient = getNorm(g)
  print(f"--The norm of the gradient vector |g(x_{count})|: {normOfGradient}")

  ## check if converged; if true, then stop; continue otherwise
  if normOfGradient <= thresh:
    break


  ## get h=-g
  h_i = -1*g
  print(f"--The h vector h_{count}: ")
  print(h_i)

  ## get the new solution point
  x_i_plus1 = x_i + alpha * h_i
  print(f"--The solution vector x_{count+1}: ")
  print(x_i_plus1)

  x_i = x_i_plus1
  count = count + 1
  print()

--The initial guess x0: 
[[ 3.]
 [-1.]
 [ 0.]
 [ 1.]]
****************************************************
--At iteration: 0
--The gradient vector g(x_0): 
[[ 306.]
 [-140.]
 [ -20.]
 [-300.]]
--The norm of the gradient vector |g(x_0)|: 451.26045694255106
--The h vector h_0: 
[[-306.]
 [ 140.]
 [  20.]
 [ 300.]]
--The solution vector x_1: 
[[ 2.694]
 [-0.86 ]
 [ 0.02 ]
 [ 1.3  ]]

****************************************************
--At iteration: 1
--The gradient vector g(x_1): 
[[  96.54283936]
 [-118.12      ]
 [ -41.94304   ]
 [ -66.41179936]]
--The norm of the gradient vector |g(x_1)|: 171.58846094759767
--The h vector h_1: 
[[-96.54283936]
 [118.12      ]
 [ 41.94304   ]
 [ 66.41179936]]
--The solution vector x_2: 
[[ 2.59745716]
 [-0.74188   ]
 [ 0.06194304]
 [ 1.3664118 ]]

****************************************************
--At iteration: 2
--The gradient vector g(x_2): 
[[ 64.98193891]
 [-96.42685679]
 [-44.39469163]
 [-30.22993296]]
--The norm of the gradient vector |g(x_

C:\Users\robin\AppData\Local\Temp\ipykernel_45336\3274413321.py:15: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return math.sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2] + v[3]*v[3])   #v[x_i]*v[x_i]


[[ 0.18113676]
 [-0.01839122]
 [-0.19862407]
 [ 0.01564818]]
--The norm of the gradient vector |g(x_490)|: 0.2698984044757152
--The h vector h_490: 
[[-0.18113676]
 [ 0.01839122]
 [ 0.19862407]
 [-0.01564818]]
--The solution vector x_491: 
[[ 1.54365326]
 [-0.154457  ]
 [ 1.16308352]
 [ 1.37781752]]

****************************************************
--At iteration: 491
--The gradient vector g(x_491): 
[[ 0.18059563]
 [-0.01833571]
 [-0.19803066]
 [ 0.01560146]]
--The norm of the gradient vector |g(x_491)|: 0.26909204045918966
--The h vector h_491: 
[[-0.18059563]
 [ 0.01833571]
 [ 0.19803066]
 [-0.01560146]]
--The solution vector x_492: 
[[ 1.54347266]
 [-0.15443867]
 [ 1.16328155]
 [ 1.37780192]]

****************************************************
--At iteration: 492
--The gradient vector g(x_492): 
[[ 0.18005718]
 [-0.01828048]
 [-0.1974402 ]
 [ 0.01555498]]
--The norm of the gradient vector |g(x_492)|: 0.26828968596905567
--The h vector h_492: 
[[-0.18005718]
 [ 0.01828048]
 [ 

As we see, our iterations are 4500, and our solution vector is as follows:  
*x* =  
[ 1.42270078]  
 [-0.14227344]  
 [ 1.29570819]  
 [ 1.36736369]  
Aka, our $x_{1}$ approaches 1, $x_{2}$ approaches -0.1, $x_{3}$ approaches 1, and $x_{4}$ approaches 1.

For part 2 of this question, what would happen if we were to change the alpha value to 0.1? Would the gradient descent still converge?  
The answer is no it would not because the polynomial contains high degree polynomial terms, which mean it's reapidly growing. Along with it being nonlinear, this makes for a function that will grow very fast and big.  
With a large alpha like 0.1, it will overshoot our minimum and will actually diverge instead of converge. Thus, no it will not converge.