<a href="https://colab.research.google.com/github/mathgod27/NumericalAnalysisProjects/blob/main/Comments_on_numpy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python list to store data**

In [ ]:
# Concatenating two lists in Python
a = [1, 2]
b = [3, 4]
a + b

[1, 2, 3, 4]

In [ ]:
# element wise add operation of two lists
def elemwise_add(v, w):
  return [v_i + w_i for v_i, w_i in zip(v, w)]

c = elemwise_add(a,b)
print(c)

[4, 6]


In [ ]:
# vector-like dot operation of two lists
def vector_dot(a,b):
  return sum([i*j for i,j in zip(a,b)])

d = vector_dot(a,b)
print(d)

11


**Numpy array to store data**

In [ ]:
import numpy as np

a_np = np.array([1,2])
b_np = np.array([3,4])

c_np = a_np + b_np
print(c_np)

d_np = np.dot(a_np , b_np)
print(d_np)

# or dot product
d2_np = a_np.dot(b_np)
print(d2_np)

[4 6]
11
11


**Caution: python name binding**

In [ ]:
e_np = np.array([1,2, 3, 4])
print(e_np)
print(e_np.shape)

[1 2 3 4]
(4,)


In [ ]:
f_np = e_np

f_np[1] = 999
print(f_np)

[  1 999   3   4]


In [ ]:
print(e_np)

print(id(f_np))
print(id(e_np))

[  1 999   3   4]
140452147071856
140452147071856


In [ ]:
# this is because of name binding
a = 2
b = a

print(a)
print(b)

# the address of an object in RAM
print(id(a))
print(id(b))

2
2
10914528
10914528


**Copy function**

In [ ]:
e_np = np.array([1,2, 3, 4])
print(e_np)
print(e_np.shape)

f_np = e_np.copy()
f_np[1] = 999

print(f_np)
print(e_np)

print(id(f_np))
print(id(e_np))

[1 2 3 4]
(4,)
[  1 999   3   4]
[1 2 3 4]
140452138272288
140452138271488


**More examples to show the usefulness of copy**

In [ ]:
e_np = np.array([[1,2, 3, 4],[5,6,7,8],[9,10,11,12]])
print(e_np)
print(e_np.shape)
print()

f_np = e_np[:,3]
f_np[1] = 999

print(f_np)
print()

print(e_np)
print()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)

[  4 999  12]

[[  1   2   3   4]
 [  5   6   7 999]
 [  9  10  11  12]]

