<a href="https://colab.research.google.com/github/mathgod27/NumericalAnalysisProjects/blob/main/LU%2BLDLt%2BCholesky_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Numpy and Scipy

* Details of the Linear algebra (scipy.linalg):https://docs.scipy.org/doc/scipy/reference/linalg.html
* Details of the NumPy linear algebra functions: https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg

In [ ]:
import numpy as np
import scipy as sp
import scipy.linalg

# LU Decomposition from scipy

* Use scipy.linalg.lu to compute pivoted LU decomposition of a matrix.

In [ ]:
# A = np.array([[6,-2,2,4],[12,-8,6,10],[3,-13,9,3],[-6,4,1,-18]])
A = np.array([[1,2,0],[3,6,-1],[1,2,1]])
print(A)
print()

P, L, U = sp.linalg.lu(A)

print(P)
print()

print(L)
print()

print(U)
print()

[[ 1  2  0]
 [ 3  6 -1]
 [ 1  2  1]]

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]

[[1.         0.         0.        ]
 [0.33333333 1.         0.        ]
 [0.33333333 0.         1.        ]]

[[ 3.          6.         -1.        ]
 [ 0.          0.          0.33333333]
 [ 0.          0.          1.33333333]]



# Solving Linear Systems Using LU from scipy

* scipy.linalg.lu_solve needs to work with scipy.linalg.lu_factor, not scipy.linalg.lu

In [ ]:
A = np.array([[6,-2,2,4],[12,-8,6,10],[3,-13,9,3],[-6,4,1,-18]])
b = np.array([[16],[26],[-19],[-34]])

lu, piv = sp.linalg.lu_factor(A)

print(lu)
print()

print(piv)
print()

x = sp.linalg.lu_solve((lu, piv), b)

print(x)
print()

[[ 12.          -8.           6.          10.        ]
 [  0.25       -11.           7.5          0.5       ]
 [ -0.5         -0.           4.         -13.        ]
 [  0.5         -0.18181818   0.09090909   0.27272727]]

[1 2 3 3]

[[ 3.]
 [ 1.]
 [-2.]
 [ 1.]]



# $LDL^T$ Decomposition from scipy
* for symmetric matrices

In [ ]:
A = np.array([[2, -1, 3], [-1, 2, 0], [3, 0, 1]])
print(A)
print()

L, D, P = sp.linalg.ldl(A)

print(L)
print()

print(D)
print()

print(P)
print()

print(np.matmul(L, np.matmul(D, L.T)))  # check if A = LDL_t

[[ 2 -1  3]
 [-1  2  0]
 [ 3  0  1]]

[[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [ 1.5  1.   1. ]]

[[ 2.   0.   0. ]
 [ 0.   1.5  0. ]
 [ 0.   0.  -5. ]]

[0 1 2]

[[ 2. -1.  3.]
 [-1.  2.  0.]
 [ 3.  0.  1.]]


# Cholesky decomposition from scipy
* for symmetric, positive definite matrices

In [ ]:
A = np.array([[2, -1, 3], [8, 2, 0], [5, 0, 1]])
B = np.matmul(A, A.T)  # get a matrix that is symmetric, positive definite

print(B)
print()

L = sp.linalg.cholesky(B, lower=True)

print(L)
print()

print(np.matmul(L, L.T))  # check if B = LL_t

[[14 14 13]
 [14 68 40]
 [13 40 26]]

[[3.74165739 0.         0.        ]
 [3.74165739 7.34846923 0.        ]
 [3.47439614 3.67423461 0.65465367]]

[[14. 14. 13.]
 [14. 68. 40.]
 [13. 40. 26.]]


# Cholesky Decomposition from numpy

In [ ]:
A = np.array([[2, -1, 3], [8, 2, 0], [5, 0, 1]])
B = np.matmul(A, A.T)  # get a matrix that is symmetric, positive definite

print(B)
print()

L = np.linalg.cholesky(B)

print(L)
print()

print(np.matmul(L, L.T))  # check if B = LL_t

[[14 14 13]
 [14 68 40]
 [13 40 26]]

[[3.74165739 0.         0.        ]
 [3.74165739 7.34846923 0.        ]
 [3.47439614 3.67423461 0.65465367]]

[[14. 14. 13.]
 [14. 68. 40.]
 [13. 40. 26.]]
