<a href="https://colab.research.google.com/github/mathgod27/NumericalAnalysisProjects/blob/main/matrices_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Numpy

In [ ]:
import numpy as np

# Obtaining Some Matrix Attributes

In [ ]:
a_mat = np.array([[1.0, 2.0], [3, 4], [5, 6]])

print(a_mat.shape)
print(a_mat.ndim)
print(a_mat.size)
print(a_mat.dtype)
print(type(a_mat))

(3, 2)
2
6
float64
<class 'numpy.ndarray'>


# 1D ndarray vs 2D ndarray

In [ ]:
b_vec = np.array([1, 2, 3, 4, 5])
print(b_vec.shape)
print(b_vec.ndim)
print(b_vec.size)
print(b_vec.dtype)
print(type(b_vec))
print()

c_mat = np.array([[1, 2, 3, 4, 5]])
print(c_mat.shape)
print(c_mat.ndim)
print(c_mat.size)
print(c_mat.dtype)
print(type(c_mat))
print()

d_mat = np.array([[1], [2], [3], [4], [5]])
print(d_mat.shape)
print(d_mat.ndim)
print(d_mat.size)
print(d_mat.dtype)
print(type(d_mat))
print()

b_mat = b_vec[np.newaxis, :]
print(b_mat.shape)
print(b_mat.ndim)
print(b_mat.size)
print(b_mat.dtype)
print(type(b_mat))
print()

b_mat_2 = b_vec[:, np.newaxis]
print(b_mat_2.shape)
print(b_mat_2.ndim)
print(b_mat_2.size)
print(b_mat_2.dtype)
print(type(b_mat_2))
print()

(5,)
1
5
int64
<class 'numpy.ndarray'>

(1, 5)
2
5
int64
<class 'numpy.ndarray'>

(5, 1)
2
5
int64
<class 'numpy.ndarray'>

(1, 5)
2
5
int64
<class 'numpy.ndarray'>

(5, 1)
2
5
int64
<class 'numpy.ndarray'>



# Matrix Addition_Subtraction_ScalarProduct

In [ ]:
a_mat = np.array([[1, 2], [3, 4], [5, 6]])
b_mat = np.array([[7, 8], [9, 10], [11, 12]])
print(a_mat)
print()
print(b_mat)
print()


add_ = a_mat + b_mat
print(add_)
print()

sub_ = a_mat - b_mat
print(sub_)
print()

scalar_mul_ = a_mat * 3
print(scalar_mul_)

[[1 2]
 [3 4]
 [5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]

[[ 8 10]
 [12 14]
 [16 18]]

[[-6 -6]
 [-6 -6]
 [-6 -6]]

[[ 3  6]
 [ 9 12]
 [15 18]]


# Matrix Transpose

In [ ]:
a_mat = np.array([[1, 2], [3, 4], [5, 6]])
print(a_mat)
print()

a_mat_t = a_mat.transpose()
print(a_mat_t)

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]


# Creation of the Identity Matrix

In [ ]:
I = np.identity(3)
print(I)
print()

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



# Creation of a Diagonal Matrix

In [ ]:
D = np.diag([0,4,8])
print(D)
print()

[[0 0 0]
 [0 4 0]
 [0 0 8]]



# Matrix-Vector or Matrix-Matrix Multiplication

In [ ]:
a_mat = np.array([[1, 2], [3, 4], [5, 6]])
b_mat = np.array([[7, 8, 9], [10, 11,12]])
#b_mat = np.array([[7], [10]])

print(a_mat)
print()
print(b_mat)
print()

mat_mat_prod_ = np.matmul(a_mat, b_mat)
print(mat_mat_prod_)
print()

mat_mat_prod_2 = np.dot(a_mat, b_mat)
print(mat_mat_prod_2)
print()

mat_mat_prod_3 = a_mat.dot(b_mat)
print(mat_mat_prod_3)
print()

[[1 2]
 [3 4]
 [5 6]]

[[ 7  8  9]
 [10 11 12]]

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]

[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]



In [ ]:
b_vec = np.array([1, 2, 3])
print(b_vec.shape)
print(b_vec.ndim)
print(b_vec.size)
print(b_vec.dtype)
print(type(b_vec))
print()

b_mat = np.array([[1], [2], [3]])
print(b_mat.shape)
print(b_mat.ndim)
print(b_mat.size)
print(b_mat.dtype)
print(type(b_mat))
print()

a_mat = np.array([[7, 8, 9], [10, 11,12]])

mat_vec_prod_ = np.matmul(a_mat, b_vec)
print(mat_vec_prod_)
print()

mat_mat_prod_ = np.matmul(a_mat, b_mat)
print(mat_vec_prod_)
print()

(3,)
1
3
int64
<class 'numpy.ndarray'>

(3, 1)
2
3
int64
<class 'numpy.ndarray'>

[50 68]

[50 68]



# AB $\neq$ BA

In [ ]:
a_mat = np.array([[1, 2, 3], [3, 4, 4], [5, 6, 6]])
b_mat = np.array([[7, 8, 9], [10, 11,12], [13, 14, 15]])

print(a_mat)
print()
print(b_mat)
print()

a_b_prod = np.matmul(a_mat, b_mat)
print(a_b_prod)
print()

b_a_prod = np.matmul(b_mat, a_mat)
print(b_a_prod)
print()

[[1 2 3]
 [3 4 4]
 [5 6 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[ 66  72  78]
 [113 124 135]
 [173 190 207]]

[[ 76 100 107]
 [103 136 146]
 [130 172 185]]



# "numpy.matmul" vs "numpy.multiply"
Caution!!
* *numpy.matmul()* performs matrix-matrix multiplication
* *numpy.multiply()* performs **element-wise** multiplication

In [ ]:
a_mat = np.array([[1, 2, 3], [3, 4, 4], [5, 6, 6]])
b_mat = np.array([[7, 8, 9], [10, 11,12], [13, 14, 15]])

print(a_mat)
print()
print(b_mat)
print()

# matrix-matrix multiplication
mat_mat_prod_ = np.matmul(a_mat, b_mat)
print(mat_mat_prod_)
print()

# element-wise multiplication
mat_mat_elemMul = np.multiply(a_mat, b_mat)
print(mat_mat_elemMul)
print()

[[1 2 3]
 [3 4 4]
 [5 6 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]

[[ 66  72  78]
 [113 124 135]
 [173 190 207]]

[[ 7 16 27]
 [30 44 48]
 [65 84 90]]



# Matrix Inverse

In [ ]:
a_mat = np.array([[1, 2, 1], [2, 3, 4], [2, 1, 1]])
print(a_mat)
print()

a_mat_inv = np.linalg.inv(a_mat)
print(a_mat_inv)
print()

mat_mat_prod_ = np.matmul(a_mat, a_mat_inv)
print(mat_mat_prod_)
print()

[[1 2 1]
 [2 3 4]
 [2 1 1]]

[[-0.14285714 -0.14285714  0.71428571]
 [ 0.85714286 -0.14285714 -0.28571429]
 [-0.57142857  0.42857143 -0.14285714]]

[[ 1.00000000e+00  5.55111512e-17 -5.55111512e-17]
 [ 0.00000000e+00  1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16 -5.55111512e-17  1.00000000e+00]]

