<a href="https://colab.research.google.com/github/mathgod27/NumericalAnalysisProjects/blob/main/QR_Decomposition_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Numpy

In [ ]:
import numpy as np

# QR Decomposition

In [ ]:
A = np.array([[12, -51, 4],[6, 167, -68], [-4, 24, -41]])

Q, R = np.linalg.qr(A)

print(Q)
print()

print(R)

[[-0.85714286  0.39428571  0.33142857]
 [-0.42857143 -0.90285714 -0.03428571]
 [ 0.28571429 -0.17142857  0.94285714]]

[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]
