<a href="https://colab.research.google.com/github/mathgod27/NumericalAnalysisProjects/blob/main/Singular_Value_Decomposition_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Numpy

In [ ]:
import numpy as np

# Compact SVD

In [ ]:
A = np.array([[1, 1],[0, 1], [1, 0]])

U, D, Vt = np.linalg.svd(A, full_matrices=False)

print(U)
print()

print(D)
print()

print(Vt)

[[-8.16496581e-01 -1.85577521e-16]
 [-4.08248290e-01 -7.07106781e-01]
 [-4.08248290e-01  7.07106781e-01]]

[1.73205081 1.        ]

[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]


# Full SVD

In [ ]:
A = np.array([[1, 1],[0, 1], [1, 0]])

U, D, Vt = np.linalg.svd(A, full_matrices=True)

print(U)
print()

print(D)
print()

print(Vt)

[[-8.16496581e-01 -1.85577521e-16 -5.77350269e-01]
 [-4.08248290e-01 -7.07106781e-01  5.77350269e-01]
 [-4.08248290e-01  7.07106781e-01  5.77350269e-01]]

[1.73205081 1.        ]

[[-0.70710678 -0.70710678]
 [ 0.70710678 -0.70710678]]
