<a href="https://colab.research.google.com/github/mathgod27/NumericalAnalysisProjects/blob/main/Vectors_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Numpy

In [ ]:
import numpy as np

# Vector Addition

In [ ]:
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])

add_ = a_np + b_np
print(add_)

[5 7 9]


# Vector Subtraction

In [ ]:
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])

sub_ = a_np - b_np
print(sub_)

[-3 -3 -3]


# Scalar-Vector Multiplication

In [ ]:
a_np = np.array([1,2,3])

scalar_mul_ = a_np * 3
print(scalar_mul_)

[3 6 9]


# Element-Wise Vector Multiplication

In [ ]:
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])

mul_ = a_np * b_np
print(mul_)

[ 4 10 18]


# Dot Product

In [ ]:
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])

dot_ = np.dot(a_np , b_np)
print(dot_)

32


# Computing Norm (Vector Length)

In [ ]:
a_np = np.array([1,2,3])

norm_ = np.linalg.norm(a_np)
print(norm_)

3.7416573867739413


# Vector Normalization

In [ ]:
a_np = np.array([1,2,3])

unit_ = a_np/np.linalg.norm(a_np)
print(unit_)
print()

print(np.linalg.norm(unit_))

[0.26726124 0.53452248 0.80178373]

1.0


# Cross Product

In [ ]:
a_np = np.array([1,2,3])
b_np = np.array([4,5,6])

cross_ = np.cross(a_np, b_np)
print(cross_)

[-3  6 -3]


# Gram-Schmidt Orthonormalization

In [ ]:
def gram_schmidt(X):
  Q, R = np.linalg.qr(X)
  return Q

vSet_np = np.array([[1, 1, 1], [-1, 0, 1], [1, 1, 2]])
print(vSet_np)
print()

orthonormalSet_ = gram_schmidt(vSet_np)
print(orthonormalSet_)

print(np.dot(orthonormalSet_[:,0] , orthonormalSet_[:,1]))
print(np.dot(orthonormalSet_[:,0] , orthonormalSet_[:,2]))
print(np.dot(orthonormalSet_[:,1] , orthonormalSet_[:,2]))

print(np.dot(orthonormalSet_[:,0] , orthonormalSet_[:,0]))
print(np.dot(orthonormalSet_[:,1] , orthonormalSet_[:,1]))
print(np.dot(orthonormalSet_[:,2] , orthonormalSet_[:,2]))

[[ 1  1  1]
 [-1  0  1]
 [ 1  1  2]]

[[-0.57735027 -0.40824829 -0.70710678]
 [ 0.57735027 -0.81649658  0.        ]
 [-0.57735027 -0.40824829  0.70710678]]
5.551115123125783e-17
5.551115123125783e-17
5.551115123125783e-17
1.0
1.0000000000000004
1.0
